### ISSUE TITLE
Update name origin predictions with added ISMB speakers

### ISSUE THREAD

**Issue by trang1618** [greenelab/iscb-diversity#10]
I have [updated](https://github.com/greenelab/iscb-diversity/commit/dce11c417994d24b739e5810a5ddbc7e9793d033) the [keynotes file](https://github.com/greenelab/iscb-diversity/blob/dce11c417994d24b739e5810a5ddbc7e9793d033/data/iscb/keynotes.tsv) and files in the [data/names directory](https://github.com/greenelab/iscb-diversity/tree/dce11c417994d24b739e5810a5ddbc7e9793d033/data/names) with added ISMB speakers before 2002. Could we update the [LSTM_results_authors.tsv](https://github.com/greenelab/wiki-nationality-estimate/blob/master/data/LSTM_results_authors.tsv) for some of these new names, please? (A few are duplicated but there are some new names.)

@arielah @dhimmel

**Comment by dhimmel** [comment]
Looks like https://github.com/greenelab/iscb-diversity/commit/dce11c417994d24b739e5810a5ddbc7e9793d033 updated `data/names/full-names.tsv.xz`, so @arielah if you just update the commit hash for the data version and rerun the predictions... that is what we need.

**Comment by trang1618** [comment]
@arielah So with the newest updates, I should use the predictions from [NamePrism_results_authors.tsv](https://github.com/greenelab/wiki-nationality-estimate/blob/master/data/NamePrism_results_authors.tsv) instead of LSTM_results_authors.tsv as linked to above, is that correct? 

Would that contain both keynotes and authors? Or should I use [NamePrism_results_test.tsv](https://github.com/greenelab/wiki-nationality-estimate/blob/master/data/NamePrism_results_test.tsv)?

**Comment by arielah** [comment]
For the latest results, you'll want NamePrism_results_authors.tsv and NamePrism_results_keynotes.tsv. LSTM_results_authors.tsv and LSTM_results_keynotes.tsv should be the results with the classifier we used in the preprint publication. 

You can ignore NamePrism_results_test.tsv, that's a subset of the wiki dataset used to evaluate the classifier.

**Comment by trang1618** [comment]
Resolved here https://github.com/greenelab/wiki-nationality-estimate/pull/14.
