### ISSUE TITLE
Use binder for the ipython notebooks and Rmds?

### ISSUE THREAD

**Issue by trang1618** [greenelab/iscb-diversity#11]
It would be neat to have binder badges for our python + R analysis code. See the README [here](https://github.com/binder-examples/r_with_python).

I'm unsure how this interacts with the existing Dockerfile, but perhaps switching to Binder reduces some work on the user's side?

**Comment by dhimmel** [comment]
I've enabled binder for some repos in the past, for example at https://mybinder.org/repo/dhimmel/biorxiv-licenses. I haven't found it very useful for the following reasons:

1. it's slow to load, and sometimes the session gets interrupted. Reliability problems.
2. there's no easy way to save changes back to a git repository. Not good for actual development, just cursory exploration.

That being said, it's a nice way to allow anyone to get up and running with the code and data quickly. The other benefit is that it that it makes sure that we're specifying our dependencies... we still have to add our R dependencies to the environment right?

It looks like it might be possible to have mybinder install a python and R environment side-by-side, but expect some setup difficulty:

References:

- https://mybinder.readthedocs.io/en/latest/using.html#preparing-a-repository-for-binder
- https://github.com/binder-examples/r
- https://github.com/binder-examples/requirements
- https://github.com/binder-examples/multi-language-demo

**Comment by trang1618** [comment]
> we still have to add our R dependencies to the environment right?

Correct. Maybe instead of binder, we instead add R dependencies and perhaps a rocker image?

**Comment by dhimmel** [comment]
> Correct. Maybe instead of binder, we instead add R dependencies and perhaps a rocker image?

Yeah, I think the question is whether we have a single docker image that exposes both a jupyter notebook and an Rstudio, or two docker images (one for python, and one for R).

**Comment by trang1618** [comment]
Docker is added in https://github.com/greenelab/iscb-diversity/pull/13.
