### ISSUE TITLE
Duplicate fore_name in combine-names

### ISSUE THREAD

**Issue by trang1618** [greenelab/iscb-diversity#3]
In the [06.combine-names.ipynb notebook](https://github.com/greenelab/iscb-diversity/blob/0cf8d333432ebd655b28f07dec2f73d41c931d40/06.combine-names.ipynb), `simple_fore_name_df `seems to have duplicate `fore_name` rows with a different `n_authors` (98 pairs to be exact). This may be problematic for downstream joining/merging of dataframes.

<img width="419" alt="duplications" src="https://user-images.githubusercontent.com/1679452/72384972-816ff000-36ec-11ea-8645-2f498ec3530b.png">

**Comment by dhimmel** [comment]
There are no duplicates according to:

```python
simple_fore_name_df.fore_name.duplicated().any()
```

It looks like the issue is that fore_name sometimes has trailing (and possibly leading space):

```python
simple_fore_name_df.query("fore_name_simple == 'aaron'").fore_name.to_list()
```

An excerpt from the output:

```
 'Aaron E',
 'Aaron E ',
 'Aaron E.',
```

So probably you're stripping whitespace when reading in the files. As long as you do this consistently, it shouldn't be a problem. I'll review the processing pipeline to see if we should address this at an earlier stage.

**Comment by dhimmel** [comment]
What if we add `fore_name_simple` and `last_name_simple` to `pmc/authors.tsv.xz`, `pubmed/authors.tsv.xz`, and `keynotes.tsv`, and then your R packages do not have to worry about mapping names at all?

The downside is increased redundancy in storage and having to import `pubmedpy.names.simplify_*_name` in more places. But it'd be nice to read in the author files and immediately perform simplified names analyses.

@trang1618  what do you think?

**Comment by trang1618** [comment]
I don't love the redundancy in storage. The current R script works for now. I guess I was expecting `simple_fore_name_df` to consider `' 'Aaron E'`, `'Aaron E '` and 'Aaron E.' the same, but I see your point.

I'm fine with closing this issue. It's good to keep in mind that `read_csv()` strips the leading/trailing spaces.

**Comment by dhimmel** [comment]
> It's good to keep in mind that read_tsv() strips the leading/trailing spaces.

We could write the files with quotes if we wanted to make the read behavior more consistent, but I think it's okay as is.
