### ISSUE TITLE
Israel/SouthAsian proportion

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity#5]
The results currently say: "The proportion of keynote speakers of African, Muslim, and Hispanic origin were also slightly smaller than the field of computational biology as a whole, as represented by corresponding authors in major journals."

In the "OtherCategories" plot, we see an increase over time among honorees. Is this driven by the fraction attributable to Israel and SouthAsian? If so, should we break those out separately along with CelticEnglish, European, and EastAsian? That way "Other" would include the ones listed and we could directly refer to that figure panel?

**Comment by trang1618** [comment]
I have not revised the added text in Results. I think it's difficult to make that statement with so few data points and the imperfect accuracy of our prediction. For example, in the Hispanic panel, there are 9 years the confidence intervals cross the mean of the field. I can include this figure in Supplement, but I think we should remove this sentence. I will go over this section after finalizing the figures. 

![region](https://user-images.githubusercontent.com/1679452/73138569-008cee80-4032-11ea-9f7a-3271ddefc1eb.png)

**Comment by cgreene** [comment]
Ok! I am fine with removing that sentence if we want. I think we should find a way to say that just because a nationality isn't underrepresented against the field doesn't mean scientists from that nationality are appropriately represented. I tried to, with my edits to the conclusions, get to discussing equity in addition to simply representation. This probably is a good supplementary figure that we can point to, and I agree with the other changes that you propose around how we talk about these results!

**Comment by cgreene** [comment]
I'm going to close this - I agree with your plan!

**Comment by trang1618** [comment]
>  just because a nationality isn't underrepresented against the field doesn't mean scientists from that nationality are appropriately represented

I agree! This is what I was trying to say on gender by referring to the literature showing that what we're calculating as "the field" may already have some biases.
