### ISSUE TITLE
LSTM Output / Author Formatting Differences

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity#6]
From a few spot checks of the output, the precise formatting of names can produce some differences in output probabilities:
> Olga G Troyanskaya	0.0009172719	0.089355126	0.002170988	0.87450653	0.026625896	0.0006956403	0.005126848	0.00060157594
> Olga Troyanskaya	0.00017359722	0.008323358	0.0009031233	0.9697692	0.010842669	0.00083660573	0.009048955	0.00010252203
> Olga G. Troyanskaya	0.00047287543	0.025816487	0.0018206865	0.9362359	0.025953555	0.0017355169	0.007751918	0.0002130557

We should make sure that the names that we're supplying to the LSTM follow a consistent format between the honorees and authors.

**Comment by dhimmel** [comment]
Hmm. Column names from [full-names.tsv.xz](https://github.com/greenelab/iscb-diversity/blob/ba5f3f1b6601a6ca33d6d953df83a9a56ad5c452/data/names/full-names.tsv.xz)

```
fore_name	last_name	fore_name_simple	last_name_simple	full_name
```

And here are Troyanskayas:

```
xzcat full-names.tsv.xz | grep "Troyanskaya"
Olga G	Troyanskaya	olga	troyanskaya	Olga G Troyanskaya
Olga	Troyanskaya	olga	troyanskaya	Olga Troyanskaya
Olga G.	Troyanskaya	olga	troyanskaya	Olga G Troyanskaya
Olga	G. Troyanskaya	olga	g. troyanskaya	Olga G Troyanskaya
```

I thought we were making predictions on the final column ("full_name"). @arielah and @trang1618 is that not the case?

**Comment by dhimmel** [comment]
See Cell 4 in [`06.combine-names.ipynb`](https://github.com/greenelab/iscb-diversity/blob/54d19c80307a07c321b88e6defa4fe12093ecf5f/06.combine-names.ipynb). We have this `clean_full_name` function:

```python
def clean_full_name(name: str) -> str:
    """
    Lightly clean full names by replacing periods with spaces
    and standardizing whitespace.
    """
    name = name.replace(".", " ")
    name = " ".join(name.split())
    return name
```

I was thinking we should apply this function to all names, both from wikipedia and for authors (which has been done if we use the `full_name` column here).

**Comment by dhimmel** [comment]
It looks like `wiki-nationality-estimate` is using full_name as per:

https://github.com/greenelab/wiki-nationality-estimate/blob/24c8508d47ccb0f5f08ebf99b745fea2389ccf6a/07.test-ismb-data.py#L23-L26

But we haven't updated the version of full-names we're using as per:

https://github.com/greenelab/wiki-nationality-estimate/blob/3f7567a098434b6310b030fefc60d9cc1408066b/utils.py#L3

Still pinned to 3db643c88b72f821918e13404d09d6983dfc073c, which is one commit before clean_full_names was implemented.

@arielah can we update the commit and rerun predictions?

**Comment by dhimmel** [comment]
And just to confirm, @arielah wikipedia names did have the periods stripped as per [`03.process-wiki-output.py`](https://github.com/greenelab/wiki-nationality-estimate/blob/3f7567a098434b6310b030fefc60d9cc1408066b/03.process-wiki-output.py#L6)? So it doesn't make a ton of sense to make predictions on names with periods?

**Comment by dhimmel** [comment]
@trang1618 predictions are updated in https://github.com/greenelab/wiki-nationality-estimate/commit/a92a37284ef5a097c3f499fef782fd20f40e050c. Can you rerun our results that depend on these predictions?

I am actually not sure how you succeeded in mapping full names prior to this data update!

**Comment by trang1618** [comment]
@dhimmel We're merging on full names, correct? (first column here: https://raw.githubusercontent.com/greenelab/wiki-nationality-estimate/a92a37284ef5a097c3f499fef782fd20f40e050c/data/LSTM_results_authors.tsv)

**Comment by dhimmel** [comment]
> We're merging on full names, correct? 

Yes, we should do the following joins:

1. LSTM_results_authors.tsv with all-authors.tsv on `full_name`. We should make sure all unique, non-missing full_name values received predictions.
2. the preceding table with `corresponding-authors.tsv` on `fore_name` and `last_name`.

**Comment by trang1618** [comment]
[Updated](https://github.com/greenelab/iscb-diversity/commit/7fe01f05089e4a3153fd0d429b668bac5cdb5471).

**Comment by trang1618** [comment]
> LSTM_results_authors.tsv with all-authors.tsv on full_name. We should make sure all unique, non-missing full_name values received predictions.

You meant `full-names.tsv.xz` not `all-authors.tsv` right?

**Comment by dhimmel** [comment]
> You meant full-names.tsv.xz not all-authors.tsv right?

Yes my bad.

Thanks for the update in https://github.com/greenelab/iscb-diversity/commit/7fe01f05089e4a3153fd0d429b668bac5cdb5471. Differences to the results are minimal. Corresponding authors are slightly more European and less Celtic English. GitHub Image Swipe view is super helpful here!
