### ISSUE TITLE
Unknown country code 

### ISSUE THREAD

**Issue by trang1618** [greenelab/iscb-diversity#9]
In [data/names/corresponding-authors.tsv.xz](https://github.com/greenelab/iscb-diversity/blob/5213ba3451520af3967f74d8f58553dade0a826c/data/names/corresponding-authors.tsv.xz), for PMID 30908487, Damien F. Meyer has two country affiliations, FR (France) and GP, which is not a valid iso_2 country code.

The [Pubmed entry](https://www.ncbi.nlm.nih.gov/pubmed/30908487) points both affiliations of this author to France, so I'm not sure why this is the case.

**Comment by dhimmel** [comment]
Our country detection algorithm looks to have detected Guadeloupe in "1 CIRAD, UMR ASTRE, Petit-Bourg, **Guadeloupe**, France". Affiliation from https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6448907/.

Looks like GP is a two-letter code for Guadeloupe according to https://laendercode.net/en/country/gp. Perhaps some datasets will consider Guadeloupe as its own country and some will consider it part of France. Probably not a big deal to ignore this.

**Comment by trang1618** [comment]
Yup! Sounds like the author will be affiliated with France 100% either way.
